// Generated by Framer (c2a8602)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1lqvwvm", mediaQuery: "(min-width: 1200px)"}, {hash: "16ne04", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "yhc3hj", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {PbaUBmoUz: "valuegridtrigger"}, robots: "max-image-preview:large", serializationId: "framer-O75Ra", title: siteMetadata(params, activeLocale).title || "About", viewport: "width=device-width"}
}

export const metadataVersion = 1