// Generated by Framer (47ebf4a)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "o1tt4e", mediaQuery: "(min-width: 1200px)"}, {hash: "17oeup9", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1jz6fml", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-tUjPs", title: siteMetadata(params, activeLocale).title || "Blog", viewport: "width=device-width"}
}

export const metadataVersion = 1