// Generated by Framer (fb31e5e)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const IBe3aR3or = params?.IBe3aR3or
return {breakpoints: [{hash: "nagv7l"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-jHK8c", title: `${IBe3aR3or !== undefined ? toString(IBe3aR3or) : "{{IBe3aR3or}}"} - My Framer Site`, viewport: "width=1200"}
}

export const metadataVersion = 1