// Generated by Framer (fb31e5e)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "gxl7qu"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-7JYpq", title: siteMetadata(params, activeLocale).title || "Blog", viewport: "width=1200"}
}

export const metadataVersion = 1