// Generated by Framer (013b13c)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "knhgcc", mediaQuery: "(min-width: 1200px)"}, {hash: "11g2h1k", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "mkjrp1", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, framerSearch: {index: false}, robots: "noindex", serializationId: "framer-XtYmW", title: siteMetadata(params, activeLocale).title || "404", viewport: "width=device-width"}
}

export const metadataVersion = 1