// Generated by Framer (fb31e5e)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const n7Sf5Nmsf = params?.n7Sf5Nmsf
return {breakpoints: [{hash: "x54508"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-zZhrG", title: `${n7Sf5Nmsf !== undefined ? toString(n7Sf5Nmsf) : "{{n7Sf5Nmsf}}"} - My Framer Site`, viewport: "width=1200"}
}

export const metadataVersion = 1