// Generated by Framer (fb31e5e)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "103ww81"}], description: siteMetadata(params, activeLocale).description, elements: {QPEdPQZp4: "cases"}, robots: "max-image-preview:large", serializationId: "framer-NLfdk", title: siteMetadata(params, activeLocale).title || "Blog", viewport: "width=1200"}
}

export const metadataVersion = 1