// Generated by Framer (c2a8602)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "72rtr7", mediaQuery: "(min-width: 1200px)"}, {hash: "v1j9k2", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "1v36vhg", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {cSpqxPMrH: "custom-projects", frb2UA_Bc: "workflow-automation", HKj7t7ald: "sales-and-marketing", qb45zXZQN: "benefittrigger", qizyG_qil: "pricing", shuBCQJ3E: "services", tLZ8fl8WB: "benefits", VbpvSESbT: "cases", WupIYJn0v: "process", yvyVUvNav: "ai-assistant"}, robots: "max-image-preview:large", serializationId: "framer-Sif6X", title: siteMetadata(params, activeLocale).title || "Home", viewport: "width=device-width"}
}

export const metadataVersion = 1