// Generated by Framer (47ebf4a)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const Hy_0nvWr3 = params?.Hy_0nvWr3
return {breakpoints: [{hash: "v1xxdr", mediaQuery: "(min-width: 1200px)"}, {hash: "srr0k0", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "8y6pbe", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-YPYoS", title: `${Hy_0nvWr3 !== undefined ? toString(Hy_0nvWr3) : "{{Hy_0nvWr3}}"} - My Framer Site`, viewport: "width=device-width"}
}

export const metadataVersion = 1