// Generated by Framer (c2a8602)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "epjf54", mediaQuery: "(min-width: 1200px)"}, {hash: "1n90ssl", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "1yki1wv", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-cayKS", title: siteMetadata(params, activeLocale).title || "Contact", viewport: "width=device-width"}
}

export const metadataVersion = 1